### ISSUE TITLE
Invalid Nonce

### ISSUE THREAD

**Issue by memsjava** [Aionoso/Krakipy#1]
krakipy.krakipy.KrakenAPIError: ['EAPI:Invalid nonce']
I cant specify nonce value when instanciate the API.

**Comment by Alcatergit** [comment]
When using krakipy correctly you do not need to do so as it is done automatically. If it does not work then you can try to use a new API key.

**Comment by Aionoso** [comment]
When using krakipy correctly you do not need to do so as it is done automatically. If it does not work then you can try to use a new API key.
